# Theta Figures

# Need to recalculate agreement acceptance cutoff point

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(knitr)
library(stargazer)
library(reshape2)
library(cowplot)
library(akima)
library(patchwork)
```

```{r}

M_ab_sens = read.csv(here("data","outputs","high_high","theta_Mab_rev2.csv")) %>% add_column(theta = "M_ab") %>% rename(value = M_ab)
M_ba_sens = read.csv(here("data","outputs","high_high","theta_Mba_rev2.csv")) %>% add_column(theta = "M_ba") %>% rename(value = M_ba)
D_ab_sens = read.csv(here("data","outputs","high_high","theta_Dab_rev2.csv")) %>% add_column(theta = "D_ab") %>% rename(value = D_ab)
D_ba_sens = read.csv(here("data","outputs","high_high","theta_Dba_rev2.csv")) %>% add_column(theta = "D_ba") %>% rename(value = D_ba)

df = bind_rows(M_ab_sens, M_ba_sens, D_ab_sens, D_ba_sens) %>% 
  mutate(NPV_coop = (NPV_a_star + NPV_b_star)) %>%
  mutate(reserve_npv_coop = -(NPV_ea_star - NPV_coop)) %>% 
  mutate(NPV_coop = ifelse(x_b_so == e_star_b, NPV_ea_star, NPV_coop)) %>%
  mutate(x_coop = (x_a_so + x_b_so)) %>% 
  mutate(x_soa = (x_a_soa + x_b_soa)) %>% 
  mutate(x_coop = ifelse(x_b_so == e_star_b, x_soa, x_coop))

high_high_df = df %>% add_column(scenario = "high_high")
#low_high_df = df %>% add_column(scenario = "low_high")
#high_low_df = df %>% add_column(scenario = "high_low")
#low_low_df = df %>% add_column(scenario = "low_low")

mvmt_sens = bind_rows(high_high_df, low_high_df, high_low_df, low_low_df)

# Agreement acceptance shows the difference between non-cooperative outcome and marine reserve agreement (NPV_ea_star) - (NPV_a_hat + NPV_b_hat))
# What about the difference between non-cooperative outcome and cooperative agreement? (NPV_a_star + NPV_b_star) - (NPV_a_hat + NPV_b_hat)

```

### FIGURE 2 ###

```{r}

# Import Original Values
low_low_orig <- low_low_df %>% filter(theta == "D_ab" & theta == "D_ba" & theta == "M_ba" & theta == "M_ab" | value==0.2) %>% select(-V_a_star, -V_b_star, -theta) %>% distinct()
low_high_orig <- low_high_df %>% filter(theta == "D_ab" & theta == "D_ba" | value==0.8 & theta == "M_ab" & theta == "M_ba" | value==0.2) %>% select(-theta) %>% distinct()
high_low_orig <- high_low_df %>% filter(theta == "D_ab" & theta == "D_ba" | value==0.2 & theta == "M_ab" & theta == "M_ba" | value==0.8) %>% select(-theta) %>% distinct()
high_high_orig <- high_high_df %>% filter(theta == "D_ab" & theta == "D_ba" & theta == "M_ab" & theta == "M_ba" | value==0.8) %>% select(-theta) %>% distinct()

original_vals <- bind_rows(low_low_orig, low_high_orig, high_low_orig, high_high_orig) %>% 
  mutate(NPV_coop = (NPV_a_star + NPV_b_star)) %>%
  mutate(reserve_npv_coop = -(NPV_ea_star - NPV_coop)) %>% 
  mutate(NPV_non = NPV_a_hat + NPV_b_hat) %>%
  mutate(NPV_coop = ifelse(x_b_so == e_star_b, NPV_ea_star, NPV_coop)) %>%
  mutate(x_coop = (x_a_so + x_b_so)) %>% 
  mutate(x_soa = (x_a_soa + x_b_soa)) %>% 
  mutate(x_coop = ifelse(x_b_so == e_star_b, x_soa, x_coop))

pal4 <- c("#CB2314", "#FAD510", "#273046", "#354823", "#1E1E1E")

for_graph = original_vals %>%
  select(scenario, NPV_non, NPV_ea_star, NPV_coop) %>% 
  group_by(scenario) %>% 
  summarize(sum_NPV_non = mean(NPV_non),
            sum_NPV_ea_star = mean(NPV_ea_star), 
            sum_NPV_coop = mean(NPV_coop)) %>% 
  pivot_longer(cols = c(sum_NPV_non, sum_NPV_ea_star, sum_NPV_coop), names_to = "Category", values_to = "Value_X") 

# Create a vector with the desired label order
label_order <- c("low_low", "low_high", "high_low", "high_high")
for_graph$scenario <- factor(for_graph$scenario, levels = label_order)

bar_plot_original <- ggplot(for_graph, aes(x = scenario, y = Value_X, fill = Category)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(
    name = "",
    labels = c("Cooperative", "Marine Reserve", "Non-Cooperative"),
    values = c("sum_NPV_coop" = "#CB2314", "sum_NPV_ea_star" = "#FAD510", "sum_NPV_non" = "#273046")
  ) +
  scale_x_discrete(
    labels = c("Low Movement \nLow Dispersal", "Low Movement \nHigh Dispersal", "High Movement \nLow Dispersal", "High Movement \nHigh Dispersal")
  ) +
  theme_minimal() +
  labs(x = "Life History Strategy", y = "Mean Net Present Value")

bar_plot_original

```

```{r}

ggsave(here("visuals","output","bar_plot_original_rev2.jpg"), bar_plot_original, width = 8, height = 6)

```

### FIGURE 3 ###

# Plot of individual parameters

```{r}

# Create a vector with the desired label order
label_order <- c("M_ab", "M_ba", "D_ab", "D_ba")
# Convert the 'theta' variable to a factor with the desired label order
high_high_df$theta <- factor(high_high_df$theta, levels = label_order)
pal <- c("#3B9AB2", "#78B7C5", "#EBCC2A", "#E1AF00") #, "#EF5703", "#F21A00", "#A5C2A3", "#BDC881")

geom_ribbon = high_high_df %>% 
  mutate(coop_mgmt = NPV_coop - (NPV_a_hat + NPV_b_hat)) %>% 
  mutate(add_value = accept + NPV_coop) %>% 
  group_by(theta, value) %>% 
  summarize(min_accept = min(accept),
            max_accept = max(accept),
            mean_accept = mean(accept),
            coop_mgmt = mean(accept) + mean(reserve_npv_coop))

geom_start = geom_ribbon %>% 
  filter(theta == "M_ba" & value == 0.8 | theta == "M_ab" & value == 0.8 | theta == "D_ba" & value == 0.8 |theta == "D_ab" & value == 0.8)

high_high <- ggplot(geom_ribbon, aes(x = value, y = mean_accept, color = theta)) +
  theme_minimal() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  geom_line(size=1.5) +
  geom_line(aes(x = value, y = coop_mgmt), linetype = "dotted", color = "black") + # Dotted line represents the 'value' of an agreement (reserve NPV relative to cooperative solution NPV)
  geom_ribbon(aes(ymin = min_accept, ymax = max_accept), alpha = 0.1, color="lightgrey") +
  geom_point(data = geom_start, aes(x = value, y = mean_accept), shape = 19, size = 2, color = "black") +
  labs(x = "Stock Mobility Parameter", y = "Agreement Value (WTP-WTA)") +
  scale_color_manual(
    name = "Stock Mobility",
    labels = c("Movement to Reserve Patch (A to B)", "Movement to Fishing Patch (B to A)", "Dispersal to Reserve Patch (A to B)", "Dispersal to Fishing Patch (B to A)"),
    values = setNames(pal, unique(high_high_df$theta))
  ) +
  facet_wrap(~theta, scales = "free", ncol = 1) +
  ggtitle("High Movement, High Dispersal") +
  theme(strip.text.x = element_blank()) #+
  #theme(legend.position="none")
high_high

```

```{r}

combined_plot <- low_low + low_high + high_low + high_high +
  plot_layout(ncol = 4)
combined_plot

ggsave(here("visuals","output","params_summary_ordered_rev2.jpg"), combined_plot, width = 15, height = 9)

```

### FIGURE 4 ###

# Conservation Value Plot (NPV)

```{r}

theta_stacked3 <- mvmt_sens %>% 
  mutate(NPV_non = NPV_a_hat + NPV_b_hat) %>%
  select(theta, value, scenario, NPV_non, NPV_coop, NPV_ea_star) %>% 
  mutate(NPV_res_to_coop = ((NPV_ea_star - NPV_coop)/NPV_coop)*100) %>% 
  select(theta, value, scenario, NPV_res_to_coop) %>% 
  pivot_longer(cols = c(NPV_res_to_coop), names_to = "Category", values_to = "Value_X") %>% 
  group_by(theta, value, scenario, Category) %>% 
  summarize(mean_Value_X = mean(Value_X))

pal2 <- c("#7b3294", "#c2a5cf", "#fdb863", "#e66101")

diff_npv <- ggplot() +
  geom_line(data = theta_stacked3, aes(x = value, y = mean_Value_X, color = scenario, 
                                       linetype = case_when(
                                         scenario == "high_low" & theta == "M_ba" & value <= 0.2  ~ "1",
                                         scenario == "low_high" & theta == "M_ba" & value <= 0.1  ~ "1",
                                         scenario == "low_low" & theta == "M_ba" & value <= 0.2  ~ "1",
                                         scenario == "low_low" & theta == "M_ab" & value <= 0.3  ~ "1",
                                         scenario == "low_low" & theta == "D_ab" & value <= 0.5  ~ "1",
                                         scenario == "low_low" & theta == "D_ba" & value <= 0.3  ~ "1",
                                         TRUE ~ "2")), size=1) +
  geom_line(data = theta_stacked3, aes(x = value, y = mean_Value_X, color = scenario, 
                                       linetype = case_when(
                                         scenario == "high_low" & theta == "M_ba" & value >= 0.2  ~ "2",
                                         scenario == "low_high" & theta == "M_ba" & value >= 0.1  ~ "2",
                                         scenario == "low_low" & theta == "M_ba" & value >= 0.2  ~ "2",
                                         scenario == "low_low" & theta == "M_ab" & value >= 0.3  ~ "2",
                                         scenario == "low_low" & theta == "D_ab" & value >= 0.5  ~ "2",
                                         scenario == "low_low" & theta == "D_ba" & value >= 0.3  ~ "2",
                                         TRUE ~ "1")), size=1) +
  scale_color_manual(
    name = "Stock Mobility",
    labels = c("High Movement, High Dispersal", "High Movement, Low Dispersal", "Low Movement, High Dispersal", "Low Movement, Low Dispersal"),
    values = c("high_high" = "#e66101", "high_low" = "#fdb863", "low_high" = "#c2a5cf", "low_low" = "#7b3294")
  ) +
  labs(x = "Stock Mobility Parameter", y = "Change in Net Present Value (%)") +
  theme_minimal() +
  geom_hline(yintercept=0, linetype="dashed") +
  facet_wrap(~theta, scales = "free", ncol = 2, labeller = labeller(theta = c(
  "D_ab" = "Dispersal to Reserve Patch (A to B)",
  "D_ba" = "Dispersal to Fishing Patch (B to A)",
  "M_ab" = "Movement to Reserve Patch (A to B)",
  "M_ba" = "Movement to Fishing Patch (B to A)"))) +
  #ggtitle("Change from Cooperative NPV to Reserve NPV") +
  theme(strip.text = element_text(size = 8)) +
  scale_linetype_manual(
    name = "Line Type",
    values = c(
      "1" = "dotted",
      "2" = "solid"
    )
  ) +
  guides(linetype = FALSE)

diff_npv

```

# Comparing non-cooperative stock sizes (x_a_non + x_b_non) to Patch A as sole owner stock size.

```{r}

theta_stacked3 <- mvmt_sens %>%  
  mutate(x_ab_so = x_coop) %>% 
  mutate(x_ab_non = x_a_non + x_b_non) %>% 
  mutate(x_ab_res = x_soa) %>%
  select(theta, value, scenario, x_ab_so, x_ab_non, x_ab_res) %>% 
  mutate(stock_res_to_coop = ((x_ab_res - x_ab_so)/x_ab_so)*100) %>% 
  select(theta, value, scenario, stock_res_to_coop) %>% 
  pivot_longer(cols = c(stock_res_to_coop), names_to = "Category", values_to = "Value_X") %>% 
  group_by(theta, value, scenario, Category) %>% 
  summarize(mean_Value_X = mean(Value_X))


pal2 <- c("#7b3294", "#c2a5cf", "#fdb863", "#e66101")
pal3 <- c("#A5C2A3", "#BDC881", "#f4a582", "#EF5703")

diff_stock <- ggplot() +
  geom_line(data = theta_stacked3, aes(x = value, y = mean_Value_X, color = scenario, 
                                       linetype = case_when(
                                         scenario == "high_low" & theta == "M_ba" & value <= 0.2  ~ "2",
                                         scenario == "low_high" & theta == "M_ba" & value <= 0.1  ~ "2",
                                         scenario == "low_low" & theta == "M_ba" & value <= 0.2  ~ "2",
                                         scenario == "low_low" & theta == "M_ab" & value <= 0.3  ~ "2",
                                         scenario == "low_low" & theta == "D_ab" & value <= 0.5  ~ "2",
                                         scenario == "low_low" & theta == "D_ba" & value <= 0.3  ~ "2",
                                         TRUE ~ "1")), size=1) +
  geom_line(data = theta_stacked3, aes(x = value, y = mean_Value_X, color = scenario, 
                                       linetype = case_when(
                                         scenario == "high_low" & theta == "M_ba" & value >= 0.2  ~ "1",
                                         scenario == "low_high" & theta == "M_ba" & value >= 0.1  ~ "1",
                                         scenario == "low_low" & theta == "M_ba" & value >= 0.2  ~ "1",
                                         scenario == "low_low" & theta == "M_ab" & value >= 0.3  ~ "1",
                                         scenario == "low_low" & theta == "D_ab" & value >= 0.5  ~ "1",
                                         scenario == "low_low" & theta == "D_ba" & value >= 0.3  ~ "1",
                                         TRUE ~ "2")), size=1) +
  scale_color_manual(
    name = "Stock Mobility",
    labels = c("High Movement, High Dispersal", "High Movement, Low Dispersal", "Low Movement, High Dispersal", "Low Movement, Low Dispersal"),
    values = c("high_high" = "#EF5703", "high_low" = "#f4a582", "low_high" = "#BDC881", "low_low" = "#A5C2A3")
  ) +
  labs(x = "Stock Mobility Parameter", y = "Change in Total Stock (%)") +
  theme_minimal() +
  geom_hline(yintercept=0, linetype="dashed") +
  facet_wrap(~theta, scales = "free", ncol = 2, labeller = labeller(theta = c(
  "D_ab" = "Dispersal to Reserve Patch (A to B)",
  "D_ba" = "Dispersal to Fishing Patch (B to A)",
  "M_ab" = "Movement to Reserve Patch (A to B)",
  "M_ba" = "Movement to Fishing Patch (B to A)"))) +
  #ggtitle("Change from Cooperative Total Stock to Reserve Total Stock") +
  theme(strip.text = element_text(size = 8)) +
  guides(linetype = FALSE)

diff_stock

```

# Individual Stock Combination Plots

```{r}

coop_to_res <- diff_npv + diff_stock +
  plot_layout(ncol = 2)

coop_to_res

ggsave(here("visuals","output","coop_to_res_summary_rev2.jpg"), coop_to_res, width = 15, height = 5)
 
```

