# Heat Map Figures

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(knitr)
library(stargazer)
library(reshape2)
library(cowplot)
library(akima)
library(patchwork)
library(wesanderson)
```

# Identifying conditions where reserve is optimal

```{r}

mvmt_pt0 = read.csv(here("data","outputs","mvmt_pt0.csv")) 
mvmt_pt1 = read.csv(here("data","outputs","mvmt_pt1.csv")) 
mvmt_pt2 = read.csv(here("data","outputs","mvmt_pt2.csv")) 
mvmt_pt3 = read.csv(here("data","outputs","mvmt_pt3.csv")) 
mvmt_pt4 = read.csv(here("data","outputs","mvmt_pt4.csv")) 
mvmt_pt5 = read.csv(here("data","outputs","mvmt_pt5.csv")) 
mvmt_pt6 = read.csv(here("data","outputs","mvmt_pt6.csv")) 
mvmt_pt7 = read.csv(here("data","outputs","mvmt_pt7.csv")) 
mvmt_pt8 = read.csv(here("data","outputs","mvmt_pt8.csv")) 
mvmt_pt9 = read.csv(here("data","outputs","mvmt_pt9.csv")) 
mvmt_pt10 = read.csv(here("data","outputs","mvmt_pt10.csv"))

```

# Part 0. Editing final data frame so that corner solutions are fixed.

```{r}

# For every scenario, check if patch B is closed in the cooperative solution
# If yes, then you replace NPV_cooperative with NPV_reserve (so the reserve and cooperative solutions will have the same NPV), if no keep the co-operative.

full_mvmt_df = bind_rows(mvmt_pt0, mvmt_pt1, mvmt_pt2, mvmt_pt3, mvmt_pt4, mvmt_pt5, mvmt_pt6, mvmt_pt7, mvmt_pt8, mvmt_pt9, mvmt_pt10) %>% 
  select(-WTP_A, -accept) %>% 
  mutate(NPV_coop = (NPV_a_star + NPV_b_star)) %>%
  mutate(x_coop = (x_a_so + x_b_so)) %>% 
  mutate(x_soa = (x_a_soa + x_b_soa)) %>% 
  mutate(NPV_coop = ifelse(x_b_so == e_star_b, NPV_ea_star, NPV_coop)) %>% 
  mutate(x_coop = ifelse(x_b_so == e_star_b, x_soa, x_coop)) %>% 
  mutate(WTP_A = NPV_ea_star - NPV_a_hat) %>% 
  mutate(accept = WTP_A-WTA_B)

```

# Identifying equilibrium stock sizes for which a reserve agreement will be accepted
# Movement / Stock Size Plot

# Movement Plots

```{r}

#pal <- wes_palette("Zissou1", type = "continuous")
pal <- c("#3A9AB2", "#6FB2C1", "#91BAB6", "#A5C2A3", "#BDC881", "#DCCB4E", "#E3B710", "#E79805", "#EC7A05", "#EF5703", "#F11B00")

limits = c(-3400, 4300)
breaks = seq(-3400, 4300, by = 500)

# For Agreement Acceptance (both Patches)

for_stock_plot_sum = full_mvmt_df %>%
  group_by(M_ab, M_ba) %>% 
  summarize(mean_accept = mean(accept)) 

diff <- ggplot() +
  theme_minimal() +
  geom_tile(data = for_stock_plot_sum, aes(x = M_ab, y = M_ba, fill = mean_accept)) +
  scale_fill_gradientn(colours = pal, limits = limits, breaks = breaks) +
  labs(x = "Adult Movement to Reserve Patch (A to B)", y = "Adult Movement to Fishing Patch (B to A)", fill = "") +
  ggtitle("Mean Agreement Acceptance (WTP - WTA)") +
  theme(legend.position="none")
diff

# Willingness-to-Pay for Patch A

for_stock_plot_sum = full_mvmt_df %>% 
  group_by(M_ab, M_ba) %>% 
  summarize(mean_WTP_A = mean(WTP_A))

wtp <- ggplot() +
  theme_minimal() +
  geom_tile(data = for_stock_plot_sum, aes(x = M_ab, y = M_ba, fill = mean_WTP_A)) +
  scale_fill_gradientn(colours = pal, limits = limits, breaks = breaks) +
  labs(x = "Adult Movement to Reserve Patch (A to B)", y = "Adult Movement to Fishing Patch (B to A)", fill = "") +
  ggtitle("Mean Willingness-to-Pay for Patch A") +
  theme(legend.position="none")
wtp

# Willingness-to-Accept for Patch B

for_stock_plot_sum = full_mvmt_df %>% 
  group_by(M_ab, M_ba) %>% 
  summarize(mean_WTA_B = mean(WTA_B))

wta <- ggplot() +
  theme_minimal() +
  geom_tile(data = for_stock_plot_sum, aes(x = M_ab, y = M_ba, fill = mean_WTA_B)) +
  scale_fill_gradientn(colours = pal, limits = limits, breaks = breaks) +
  labs(x = "Adult Movement to Reserve Patch (A to B)", y = "Adult Movement to Fishing Patch (B to A)", fill = "") +
  ggtitle("Mean Willingness-to-Accept for Patch B")
wta
  
```

```{r}

combined_plot <- diff + wtp + wta 
  plot_layout(ncol = 3)
combined_plot_final <- combined_plot + guides(fill = guide_legend(title.position = "top", title = "Value", title.hjust = 0.5, keywidth = 2, keyheight = 1, reverse = TRUE))

#ggsave(here("visuals","output","summary_heatmap_3pan_rev.jpg"), combined_plot_final, width = 16, height = 5)

```

# Dispersal Plots

```{r}

#pal <- wes_palette("Zissou1", type = "continuous")
pal <- c("#3A9AB2", "#6FB2C1", "#91BAB6", "#A5C2A3", "#BDC881", "#DCCB4E", "#E3B710", "#E79805", "#EC7A05", "#EF5703", "#F11B00")
limits = c(500, 2700)
breaks = seq(500, 2700, by = 200)

# Agreement Acceptance

for_stock_plot_sum2 = full_mvmt_df %>%
  mutate(diff = x_soa - x_coop) %>% 
  group_by(D_ab, D_ba) %>% 
  summarize(mean_accept = mean(accept))

diff <- ggplot() +
  theme_minimal() +
  geom_tile(data = for_stock_plot_sum2, aes(x = D_ab, y = D_ba, fill = mean_accept)) +
  scale_fill_gradientn(colours = pal, limits = limits, breaks = breaks) +
  labs(x = "Larval Dispersal to Reserve Patch (A to B)", y = "Larval Dispersal to Fishing Patch (B to A)", fill = "") +
  ggtitle("Mean Agreement Acceptance (WTP - WTA)") +
  theme(legend.position="none")

# Willingness-to-Pay for Patch A

for_stock_plot_sum2 = full_mvmt_df %>% 
  group_by(D_ab, D_ba) %>% 
  summarize(mean_WTP_A = mean(WTP_A))

wtp <- ggplot() +
  theme_minimal() +
  geom_tile(data = for_stock_plot_sum2, aes(x = D_ab, y = D_ba, fill = mean_WTP_A)) +
  scale_fill_gradientn(colours = pal, limits = limits, breaks = breaks) +
  labs(x = "Larval Dispersal to Reserve Patch (A to B)", y = "Larval Dispersal to Fishing Patch (B to A)", fill = "") +
  ggtitle("Mean Willingness-to-Pay for Patch A") +
  theme(legend.position="none")

# Willingness-to-Accept for Patch B

for_stock_plot_sum2 = full_mvmt_df %>% 
  group_by(D_ab, D_ba) %>% 
  summarize(mean_WTA_B = mean(WTA_B))

wta <- ggplot() +
  theme_minimal() +
  geom_tile(data = for_stock_plot_sum2, aes(x = D_ab, y = D_ba, fill = mean_WTA_B)) +
  scale_fill_gradientn(colours = pal, limits = limits, breaks = breaks) +
  labs(x = "Larval Dispersal to Reserve Patch (A to B)", y = "Larval Dispersal to Fishing Patch (B to A)", fill = "") +
  ggtitle("Mean Willingness-to-Accept for Patch B")

```

```{r}

combined_plot <- diff + wtp + wta
  plot_layout(ncol = 3)
combined_plot

combined_plot_final <- combined_plot + guides(fill = guide_legend(title.position = "top", title = "Value", title.hjust = 0.5, keywidth = 2, keyheight = 1.5, reverse = TRUE))
combined_plot_final

ggsave(here("visuals","output","summary_heatmap_3pan_disp_rev.jpg"), combined_plot_final, width = 16, height = 5)

```

```