
## II. Load Parameters

```{r}

k_a = 100
r_a = 0.6

k_b = 100
r_b = 0.6

# Movement Parameters
M_ab = 0.2 # Adult movement A -> B 
M_ba = 0.2 # Adult movement B -> A 
M_aa = 1 - M_ab
M_bb = 1 - M_ba
D_ab = 0.2 # Larval dispersal A -> B 
D_ba = 0.2 # Larval dispersal B -> A
D_aa = 1 - D_ab
D_bb = 1 - D_ba

# High movement (0.8 both) low dispersal (0.2 both) "high low"
# Low movement (0.2 both) high dispersal (0.8 both) "low high"
# High movement (0.8 both) high dispersal (0.8 both) "high high"

# Survival Parameters
mu_a = 1
mu_b = 1
sigma_a = 1
sigma_b = 1

timesteps = 100

# Economic Parameters
p_a = 30
c_a = 20
p_b = 30
c_b = 20

# discount factor
delta = 0.95

# Adaptive parameters
size_x_a = 10 #size of the state grid A
size_x_b = 10 #size of B

T = 30 #time horizon for backward induction

small = 0.1

x_a_grid = seq(small, k_a, length.out=size_x_a)
x_b_grid = seq(small, k_b, length.out=size_x_b)

```

# Base Params for Dynamic Programming Grid

```{r}

# Find Patch A Sole Owner Scenario (e_a*)

df_all = data.frame()
V_next = matrix(0, size_x_a, size_x_b)
V = matrix(0, size_x_a, size_x_b)

for(t in T:1) {
  for(i in 1:size_x_a) {
    x_a = x_a_grid[i]
    for(j in 1:size_x_b) {
      x_b = x_b_grid[j]
      guess = x_a/2
      low = 0 #lower bound on escapement in A
      high = x_a #upper bound on escapement in A
      Thing = optim(par=guess, fn=payoff, lower=low, upper=high, x_a=x_a, x_b=x_b, V=V, method='L-BFGS-B')
      e_a_star = max(Thing$par, 0.1)
      V_star = -Thing$value
      V_next[i,j] = V_star
      df_now = data.frame(time=t, x_a=x_a, x_b=x_b, e_a_star=e_a_star, V_star=V_star)
      df_all = rbind(df_all, df_now)
    }
  }
  V = V_next
}

df_inf <- df_all %>% filter(time == 1) %>% select(-time, -V_star)

```