
# Theta Model

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(knitr)
library(stargazer)
library(reshape2)
library(cowplot)
library(akima)
```


# Non-Cooperative Scenario

```{r}

# Initialize data frame for storing results

num_rows <- length(x_a_grid) * length(x_b_grid) * timesteps * length(seq(0, 1, by = 0.1))
num_cols <- 10  
results_matrix_non <- matrix(NA_real_, nrow = num_rows, ncol = num_cols)
colnames(results_matrix_non) <- c("D_ab", "timestep", "x_a_init", "x_a", "e_hat_a", "x_b_init", "x_b", "e_hat_b", "NPV_a_hat", "NPV_b_hat")

row_counter <- 1

# Initialize variables to store NPV for each x_a and x_b combination
NPV_a_hat_total <- numeric(length = length(x_a_grid) * length(x_b_grid))
NPV_b_hat_total <- numeric(length = length(x_a_grid) * length(x_b_grid))
names(NPV_a_hat_total) <- paste0("x_a", 1:length(x_a_grid), "_x_b", 1:length(x_b_grid))
names(NPV_b_hat_total) <- paste0("x_a", 1:length(x_a_grid), "_x_b", 1:length(x_b_grid))


for(D_ab in seq(0, 1, by = 0.1)) {
      
        # Recalculate dependent variables
        D_aa = 1 - D_ab
  
# Grid search over x_a_grid and x_b_grid
for(i in seq_along(x_a_grid)) {
  for(j in seq_along(x_b_grid)) {
    
    # Initial stock values for this run
    x_a <- x_a_grid[i]
    x_b <- x_b_grid[j]
    
    # Storing initial values
    x_a_init <- x_a_grid[i]
    x_b_init <- x_b_grid[j]
    
    NPV_a_hat <- 0
    NPV_b_hat <- 0
    
    for(t in 1:timesteps) {
  
  # Calculate e_hat_a and e_hat_b
  e_hat_values <- compute_e_hat(x_a = x_a, x_b = x_b, mu_a, M_aa, sigma_a, D_aa, k_a, r_a, mu_b, M_bb, sigma_b, D_bb, k_b, r_b, delta)
  
  # Calculate harvest based on e_hat
  h_a_val = h_a(x_a, e_hat_values$e_hat_a)
  h_b_val = h_b(x_b, e_hat_values$e_hat_b)
  
  # Escapement
  e_hat_a = e_a(x_a, h_a_val)
  e_hat_b = e_b(x_b, h_b_val)
  
  # Update stocks in each patch
  x_a_new = next_x_a(e_hat_a, e_hat_b) - mu_a*M_aa*e_hat_a - mu_b*M_ba*e_hat_b + mu_a*M_aa*e_hat_a + mu_b*M_ba*e_hat_b
  x_b_new = next_x_b(e_hat_a, e_hat_b) - mu_b*M_bb*e_hat_b - mu_a*M_ab*e_hat_a + mu_b*M_bb*e_hat_b + mu_a*M_ab*e_hat_a
  
  # Value
  V_a_hat = b_a(p_a, c_a) * (x_a - e_hat_values$e_hat_a) * delta^(t-1)
  V_b_hat = b_b(p_b, c_b) * (x_b - e_hat_values$e_hat_b) * delta^(t-1)
      
  # Update NPV
  NPV_a_hat <- NPV_a_hat + V_a_hat
  NPV_b_hat <- NPV_b_hat + V_b_hat
  
  # Save results including e_hat_a and e_hat_b
  results_matrix_non[row_counter, ] <- c(D_ab, t, x_a_init, x_a, e_hat_values$e_hat_a, x_b_init, x_b, e_hat_values$e_hat_b, NPV_a_hat, NPV_b_hat)
  row_counter <- row_counter + 1
    
  # Update the stock for next iteration
  x_a <- x_a_new
  x_b <- x_b_new
}

    # Store NPV for the current x_a and x_b combination
    index <- (i - 1) * length(x_b_grid) + j
    NPV_a_hat_total[index] <- NPV_a_hat
    NPV_b_hat_total[index] <- NPV_b_hat
    
  }
}
}

df_results_non = as.data.frame(results_matrix_non) %>% filter(timestep==100) %>% select(-timestep)

```

# Cooperative Scenario (Sole Owner Both Patches Scenario)

```{r}

# Initialize data frame for storing results

num_rows <- length(x_a_grid) * length(x_b_grid) * timesteps * length(seq(0, 1, by = 0.1))
num_cols <- 10  
results_matrix_so <- matrix(NA_real_, nrow = num_rows, ncol = num_cols)
colnames(results_matrix_so) <- c("D_ab", "timestep", "x_a_init", "x_a", "e_star_a", "x_b_init", "x_b", "e_star_b", "NPV_a_star", "NPV_b_star")

row_counter <- 1

# Initialize variables to store NPV for each x_a and x_b combination
NPV_a_star_total <- numeric(length = length(x_a_grid) * length(x_b_grid))
NPV_b_star_total <- numeric(length = length(x_a_grid) * length(x_b_grid))
names(NPV_a_star_total) <- paste0("x_a", 1:length(x_a_grid), "_x_b", 1:length(x_b_grid))
names(NPV_b_star_total) <- paste0("x_a", 1:length(x_a_grid), "_x_b", 1:length(x_b_grid))

for(D_ab in seq(0, 1, by = 0.1)) {
      
        # Recalculate dependent variables
        D_aa = 1 - D_ab

# Grid search over x_a_grid and x_b_grid
for(i in seq_along(x_a_grid)) {
  for(j in seq_along(x_b_grid)) {
    
    # Initial stock values for this run
    x_a <- x_a_grid[i]
    x_b <- x_b_grid[j]
    
    # Storing initial values
    x_a_init <- x_a_grid[i]
    x_b_init <- x_b_grid[j]
    
    NPV_a_star <- 0
    NPV_b_star <- 0
    
    for(t in 1:timesteps) {
  
  # Calculate e_star_a and e_star_b
  e_star_values <- compute_e_star(x_a = x_a, x_b = x_b, p_a, c_a, mu_a, M_aa, sigma_a, D_aa, k_a, r_a, p_b, c_b, mu_b, M_ab, M_ba, sigma_b, D_ab, D_ba, delta)
  
  # Calculate harvest based on e_star
  h_a_val = h_a(x_a, e_star_values$e_star_a)
  h_b_val = h_b(x_b, e_star_values$e_star_b)
  
  # Escapement
  e_star_a = e_a(x_a, h_a_val)
  e_star_b = e_b(x_b, h_b_val)
  
  # Update stocks in each patch
  x_a_new = next_x_a(e_star_a, e_star_b) - mu_a*M_aa*e_star_a - mu_b*M_ba*e_star_b + mu_a*M_aa*e_star_a + mu_b*M_ba*e_star_b
  x_b_new = next_x_b(e_star_a, e_star_b) - mu_b*M_bb*e_star_b - mu_a*M_ab*e_star_a + mu_b*M_bb*e_star_b + mu_a*M_ab*e_star_a
  
  # Value
  V_a_star = b_a(p_a, c_a) * (x_a - e_star_values$e_star_a) * delta^(t-1)
  V_b_star = b_b(p_b, c_b) * (x_b - e_star_values$e_star_b) * delta^(t-1)
      
  # Update NPV
  NPV_a_star <- NPV_a_star + V_a_star
  NPV_b_star <- NPV_b_star + V_b_star
  
  # Save results including e_hat_a and e_hat_b
  results_matrix_so[row_counter, ] <- c(D_ab, t, x_a_init, x_a, e_star_values$e_star_a, x_b_init, x_b, e_star_values$e_star_b, NPV_a_star, NPV_b_star)
  row_counter <- row_counter + 1
    
  # Update the stock for next iteration
  x_a <- x_a_new
  x_b <- x_b_new
}

    # Store NPV for the current x_a and x_b combination
    index <- (i - 1) * length(x_b_grid) + j
    NPV_a_star_total[index] <- NPV_a_star
    NPV_b_star_total[index] <- NPV_b_star
    
  }
}
}

df_results_so = as.data.frame(results_matrix_so) %>% filter(timestep==100) %>% select(-timestep)
  

```

# I. Dynamic Programming to find Timestep = 1

```{r}

size_x_a = 10 #size of the state grid A
size_x_b = 10

x_a_grid = seq(small, k_a,length.out=10)
x_b_grid = seq(small, k_b, length.out=10)

# Find Patch A Sole Owner Scenario (e_a*)

df_all = data.frame()
V_next = matrix(0, size_x_a, size_x_b)
V = matrix(0, size_x_a, size_x_b)

for(t in T:1) {
  for(i in 1:size_x_a) {
    x_a = x_a_grid[i]
    for(j in 1:size_x_b) {
      x_b = x_b_grid[j]
      guess = x_a/2
      low = 0 #lower bound on escapement in A
      high = x_a #upper bound on escapement in A
      Thing = optim(par=guess, fn=payoff, lower=low, upper=high, x_a=x_a, x_b=x_b, V=V, method='L-BFGS-B')
      e_a_star = Thing$par
      V_star = -Thing$value
      V_next[i,j] = V_star
      df_now = data.frame(time=t, x_a=x_a, x_b=x_b, e_a_star=e_a_star, V_star=V_star)
      df_all = rbind(df_all, df_now)
    }
  }
  V = V_next
}

df_inf = df_all %>% filter(time==1) %>% select(-time, -V_star) 

```

```{r}

size_x_a = 10 #size of the state grid A
size_x_b = 10 #size of B

x_a_grid = seq(small, k_a,length.out=size_x_a)
x_b_grid = seq(small, k_b, length.out=size_x_b)

df_int = df_inf |> mutate(xab = x_a * x_b) 

interp_model <- mgcv::gam(e_a_star ~ s(x_a) + s(x_b) + s(xab), data = df_int)

interp_frame <-

    data.frame(x_a = x_a, x_b = x_b, xab = x_a * x_b)

e_a_star <- pmax(min(df_int$e_a_star),predict(interp_model, newdata = interp_frame))

# 1. Create a new dataframe for the grid values
grid_df <- expand.grid(x_a = seq(small, k_a,length.out=size_x_a), x_b = seq(small, k_b,length.out=size_x_b))

# 2. Calculate the interaction term xab for the grid
grid_df$xab <- grid_df$x_a * grid_df$x_b

# 3. Predict e_a_star for the entire grid
predicted_e_a_star <- predict(interp_model, newdata = grid_df)

# 4. Merge the interpolated e_a_star values with df_results_so_ea based on x_a and x_b
df_e_a_star_interpolated <- merge(grid_df, df_int, by.x = c("x_a", "x_b"), by.y = c("x_a", "x_b"), all.x = TRUE)

# Replace the NAs in df_results_so_ea_interpolated with the interpolated values
df_e_a_star_interpolated$e_a_star <- ifelse(is.na(df_e_a_star_interpolated$e_a_star), predicted_e_a_star, df_e_a_star_interpolated$e_a_star)

# Replace negative values of e_a_star with 0
df_e_a_star_interpolated$e_a_star <- pmax(df_e_a_star_interpolated$e_a_star, 0)

df_e_a_star_int <- df_e_a_star_interpolated %>% select(x_a, x_b, e_a_star)

print(df_e_a_star_int)

```

#II. Sole Owner Patch A (Reserve Scenario)

# Single Value

```{r}

size_x_a = 10 #size of the state grid A
size_x_b = 10 #size of B

x_a_grid = seq(small, k_a, length.out=size_x_a)
x_b_grid = seq(small, k_b, length.out=size_x_b)

num_rows <- length(x_a_grid) * length(x_b_grid) * timesteps * length(seq(0, 1, by = 0.1))
num_cols <- 9  # Number of variables you are storing
results_matrix_soa <- matrix(NA_real_, nrow = num_rows, ncol = num_cols)
colnames(results_matrix_soa) <- c("D_ab", "timestep", "x_a_init", "x_a", "e_a_star", "x_b_init", "x_b", "NPV_ea_star", "NPV_eb_star")

row_counter <- 1

# Initialize NPV variables and counter
NPV_ea_star_total <- numeric(length = length(x_a_grid) * length(x_b_grid))
NPV_eb_star_total <- numeric(length = length(x_a_grid) * length(x_b_grid))

names(NPV_ea_star_total) <- paste0("x_a", 1:length(x_a_grid), "_x_b", 1:length(x_b_grid))
names(NPV_eb_star_total) <- paste0("x_a", 1:length(x_a_grid), "_x_b", 1:length(x_b_grid))

#matrix_df = dcast(df_inf, x_a ~ x_b, value.var = "e_a_star")
#rownames(matrix_df) = x_a_grid
#matrix_df = matrix_df[, -1]

matrix_df = dcast(df_e_a_star_int, x_a ~ x_b, value.var = "e_a_star")
rownames(matrix_df) = x_a_grid
matrix_df = matrix_df[, -1]

for(D_ab in seq(0, 1, by = 0.1)) {
      
        # Recalculate dependent variables
        D_aa = 1 - D_ab

# Grid search over x_a_grid and x_b_grid
for(i in seq_along(x_a_grid)) {
  for(j in seq_along(x_b_grid)) {
    
    # Initial stock values for this run
    x_a <- x_a_grid[i]
    x_b <- x_b_grid[j]
    
    # Storing initial values
    x_a_init <- x_a_grid[i]
    x_b_init <- x_b_grid[j]
    
    # Extract e_a_star from df_inf
    e_a_star <- matrix_df[i, j]
       
    NPV_ea_star <- 0
    NPV_eb_star <- 0
    
    for(t in 1:timesteps) {
    
  initial_e_a_star <- matrix_df[i, j]
      
  e_a_star <- ifelse(matrix_df[i, j] > x_a, x_a, matrix_df[i, j])
  
  # Calculate harvest based on e_star
  h_a_val = h_a(x_a, e_a_star)
  h_b_val = h_b(x_b, x_b)
  
  # Update stocks in each patch
  x_a_new = next_x_a(e_a_star, x_b) - mu_a*M_aa*e_a_star - mu_b*M_ba*x_b + mu_a*M_aa*e_a_star + mu_b*M_ba*x_b
  x_b_new = next_x_b(e_a_star, x_b) - mu_b*M_bb*x_b - mu_a*M_ab*e_a_star + mu_b*M_bb*x_b + mu_a*M_ab*e_a_star
  
  # Value
  V_a_star = b_a(p_a, c_a) * (x_a - e_a_star) * delta^(t-1)
  V_b_star = b_b(p_b, c_b) * (x_b) * delta^(t-1)
  
  # Update NPV
  NPV_ea_star <- NPV_ea_star + V_a_star
  NPV_eb_star <- NPV_eb_star + V_b_star
  
  # Save results
  results_matrix_soa[row_counter, ] <- c(D_ab, t, x_a_init, x_a, e_a_star, x_b_init, x_b, NPV_ea_star, NPV_eb_star)
  row_counter <- row_counter + 1
    
  # Update the stock for next iteration
  x_a <- x_a_new
  x_b <- x_b_new
  
    }
    
    # Store NPV for the current x_a and x_b combination
    index <- (i - 1) * length(x_b_grid) + j
    NPV_ea_star_total[index] <- NPV_ea_star
    NPV_eb_star_total[index] <- NPV_eb_star
  }
}
}

# View results

df_results_soa = as.data.frame(results_matrix_soa) %>% filter(timestep==100) %>% select(-timestep)

```

# Calculate Final Results

```{r}

# Changing the name of x_a_init and x_b_init to just x_a and x_b for simplicity. 
df_results_non_bind = df_results_non %>% rename (x_a_non = x_a) %>% rename (x_b_non = x_b)
df_results_so_bind = df_results_so %>% rename (x_a_so = x_a) %>% rename (x_b_so = x_b)
df_results_ea_bind = df_results_soa %>% rename (x_a_soa = x_a) %>% rename (x_b_soa = x_b)

# Merging e_a_star values from df_inf into results based on x_a and x_b
results <- df_results_non_bind %>% left_join(df_results_so_bind, by= c("D_ab", "x_a_init", "x_b_init")) %>% 
  left_join(df_results_ea_bind, by= c("D_ab","x_a_init", "x_b_init")) %>% 
  mutate(WTP_A = NPV_ea_star-NPV_a_hat,
         WTA_B = NPV_b_hat) %>% 
  mutate(accept = WTP_A-WTA_B) %>% 
  mutate(reserve_npv_coop = (NPV_ea_star) - (NPV_a_star + NPV_b_star)) %>% # The difference between the gains under cooperation vs the gains under reserve
  mutate(reserve_npv_non = (NPV_ea_star) - (NPV_a_hat + NPV_b_hat)) %>% # Same as accept, the difference between the gains under non-coop vs the gains under reserve
  mutate(coop_npv_non = (NPV_a_star + NPV_b_star) - (NPV_a_hat + NPV_b_hat)) %>% 
  mutate(reserve_vs_non_x = (x_a_soa + x_b_soa) - (x_a_non + x_b_non)) %>% 
  mutate(reserve_vs_coop_x = (x_a_so + x_a_so) - (x_a_non + x_b_non)) 

results_nar <- results %>% 
  filter(accept > -1 & accept < 1)

```

```{r}

write.csv(results, here("data","outputs","high_high","theta_Dab.csv"), row.names=FALSE)

```

